# -*- coding: utf-8 -*-
"""phyton.areas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kR8weNtsj92NWwvCrWbRdpptAbVMHvq3
"""



#autor Mayra


#def area1(base,altura):  #argumentos o parametros
   # return base*altura

#despliegue-------------------------area

#b=int(input("digite la base"))
#a=int(input("digite la altura"))
#c=area(b,a)
#print(c)

#print(area1(5,3))

#print(area1(2,7))


#-----------------------------------------------------triangulo

#def triangulo(base,altura)
 #    salida=0
  #    salida=base*altura/2

   #   return salida

      #despliegue

#      b=int(input("digite la base"))
 #     a=int(input("digite la altura"))
  #    c=triangulo(a,b)
   #   print(c)

#------------------------------------area del circulo

#import math

#def circulo(radio):
 #   salida=0
  #  salida=math.pi * radio ** 2
   # return salida

#radio = input("Ingrese el radio del círculo: ")
#math.pi = 3,146
#radio=float(radio)
#print(math.pi,radio)

#-------------------------------------------------horas------

def convertir_hora(hora_am_pm):
    parametros= hora_am_pm.split(':')
    hora=int(parametros[0])
    minutos=int(parametros[1])
    am_pm = parametros[2].strip() #elimina espacios en blancos


    if am_pm =="PM":
      if hora !=12:
        hora += 12

    else:
      if hora ==12:
         hora=0

         hora_militar = f"{hora:02d}:{minutos:02d}"
         return hora_militar


         hora_am_pm="02:30 PM"
         hora_militar = convertir_hora(hora_am_pm)

         print("la hora militar: ",hora_militar)